# Generated by Django 5.0 on 2024-12-13 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_App', '0002_alter_customer_user'),
        ('User_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='User_App.user'),
        ),
    ]
