# Generated by Django 5.0 on 2024-12-18 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer_App', '0003_alter_customer_user'),
        ('User_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('discount', models.FloatField()),
                ('vat', models.FloatField()),
                ('payable', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Customer_App.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='User_App.user')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
    ]
