# Generated by Django 5.0 on 2024-12-18 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice_App', '0001_initial'),
        ('Product_App', '0002_alter_product_table'),
        ('User_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sale_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Invoice_App.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Product_App.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='User_App.user')),
            ],
        ),
    ]
