# Generated by Django 5.0 on 2024-12-18 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice_App', '0002_invoiceproduct'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invoiceproduct',
            table='invoice_products',
        ),
    ]
