# Generated by Django 5.0 on 2024-12-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Products',
        ),
    ]
