# Generated by Django 5.0 on 2024-12-19 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category_App', '0002_alter_category_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='user',
            new_name='userId',
        ),
    ]
