# Generated by Django 5.0 on 2024-12-19 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category_App', '0003_rename_user_category_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='userId',
            new_name='user',
        ),
    ]
